"""Add whole_price to Product

Revision ID: 02276bee6692
Revises: 998bf4960f38
Create Date: 2025-11-02 17:47:21.494521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02276bee6692'
down_revision = '998bf4960f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bottles_sold', sa.Integer(), nullable=True))

    with op.batch_alter_table('container_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('returnable_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returnable_container', schema=None) as batch_op:
        batch_op.drop_column('total_sold')

    with op.batch_alter_table('container_transaction', schema=None) as batch_op:
        batch_op.drop_column('sold_quantity')

    with op.batch_alter_table('bottle_transaction', schema=None) as batch_op:
        batch_op.drop_column('bottles_sold')

    # ### end Alembic commands ###
