"""Add whole_price to Product

Revision ID: 5e766008e8a0
Revises: 6bce4017088b
Create Date: 2025-11-19 03:03:02.426944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e766008e8a0'
down_revision = '6bce4017088b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bottle_transaction_old')
    op.drop_table('returnable_container_old')
    op.drop_table('container_transaction_old')
    op.drop_table('sale_item_old')
    op.drop_table('purchase_order_item_old')
    with op.batch_alter_table('stock_adjustment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('container_id', sa.Integer(), nullable=True))
        batch_op.alter_column('adjustment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_foreign_key(None, 'returnable_container', ['container_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_unit', ['product_unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_adjustment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('adjustment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('container_id')
        batch_op.drop_column('product_unit_id')

    op.create_table('purchase_order_item_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_order_item_pkey_2'))
    )
    op.create_table('sale_item_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('transaction_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_item_pkey_1'))
    )
    op.create_table('container_transaction_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sold_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('container_transaction_pkey_1'))
    )
    op.create_table('returnable_container_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('unit_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_issued', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_returned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_damaged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('total_in_stock >= 0', name=op.f('check_total_in_stock_non_negative_1')),
    sa.PrimaryKeyConstraint('id', name=op.f('returnable_container_pkey_1'))
    )
    op.create_table('bottle_transaction_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bottles_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bottle_transaction_pkey_1'))
    )
    # ### end Alembic commands ###
