"""Add whole_price to Product

Revision ID: 6ebe597ba1a1
Revises: 5e766008e8a0
Create Date: 2025-11-19 09:12:07.665623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebe597ba1a1'
down_revision = '5e766008e8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_adjustment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_adjustment', schema=None) as batch_op:
        batch_op.drop_column('new_quantity')
        batch_op.drop_column('previous_quantity')

    # ### end Alembic commands ###
