"""Add whole_price to Product

Revision ID: 73a28563e7a2
Revises: c1d26df00791
Create Date: 2025-11-01 14:26:06.136693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a28563e7a2'
down_revision = 'c1d26df00791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_returnable', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_refundable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_refundable', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_returnable')

    # ### end Alembic commands ###
