"""Add whole_price to Product

Revision ID: 896dddd054db
Revises: 4671f42ed7d8
Create Date: 2025-10-27 19:37:39.950211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896dddd054db'
down_revision = '4671f42ed7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whole_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('whole_price')

    # ### end Alembic commands ###
