"""Add whole_price to Product

Revision ID: 998bf4960f38
Revises: 3e76f3cd45b0
Create Date: 2025-11-02 01:08:40.302165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998bf4960f38'
down_revision = '3e76f3cd45b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_transaction', schema=None) as batch_op:
        batch_op.alter_column('container_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_transaction', schema=None) as batch_op:
        batch_op.alter_column('container_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
